local telescope = require('telescope.builtin')
vim.keymap.set('n', '<C-f>f', telescope.find_files)
vim.keymap.set('n', '<C-f>p', telescope.git_files)
vim.keymap.set('n', '<C-f>g', function()
    telescope.grep_string({ search = vim.fn.input("Grep> ") })
end)
vim.keymap.set('n', '<C-f>o', telescope.buffers)
