local telescope = require('telescope.builtin')
vim.keymap.set('n', '<C-f>f', telescope.find_files)
vim.keymap.set('n', '<C-f>a', function() telescope.find_files({ hidden = true }) end)
vim.keymap.set('n', '<C-f>p', telescope.git_files)
vim.keymap.set('n', '<C-f>w', telescope.grep_string)
vim.keymap.set('n', '<C-f>g', telescope.live_grep)
vim.keymap.set('n', '<C-f>o', telescope.buffers)
vim.keymap.set('n', '<C-f>s', telescope.spell_suggest)

vim.keymap.set('n', '<C-f>lr', telescope.lsp_references)
vim.keymap.set('n', '<C-f>li', telescope.lsp_implementations)
vim.keymap.set('n', '<C-f>ld', telescope.lsp_definitions)
vim.keymap.set('n', '<C-f>lds', telescope.lsp_document_symbols)
vim.keymap.set('n', '<C-f>lws', telescope.lsp_workspace_symbols)
